### ISSUE TITLE
Finish Instructions - Marked Incomplete

### ISSUE THREAD

**Issue by jessicaengel451** [Ryan778/lbd-cybersecurity#1]
https://github.com/Ryan778/lbd-cybersecurity/blob/main/index.html#:~:text=%3Cp%3E%5BINCOMPLETE%20--%20todo%3A%20more%20detailed%20instructions%5D%20Read%20through%20the%20privacy%20policy%20as%20a%20tech-savvy%20consumer%20and%20click%20on%20the%20part%20of%20the%20policy%20that%20a%20company%20shouldn%27t%20do%20/%20seems%20ethically%20wrong.%3C/p%3E

Finish this instruction on line #34

**Comment by remzh** [comment]
Completed, merged in #4
