### ISSUE TITLE
BUG - Sentence look fine window not disappearing

### ISSUE THREAD

**Issue by jessicaengel451** [Ryan778/lbd-cybersecurity#3]
![image](https://user-images.githubusercontent.com/72846465/144170962-e58573f2-6a18-4716-afea-0eb202ae0411.png)

After you finish the game the box is still there. After they click the right one it should disappear.

**Comment by remzh** [comment]
Fixed in bdb5749bb1d3042eade4d1bbeaa6c38b264cd636
